# Type stubs for ai_query_interface module
from typing import Any, Dict, List

class AIQueryInterface:
    def __init__(self) -> None: ...
    def execute_query(self, query: str) -> Dict[str, Any]: ...
    def process_natural_language_query(self, query: str) -> Dict[str, Any]: ...
    def get_query_results(self, query_id: str) -> List[Dict[str, Any]]: ...
