# Type stubs for ai_report_generator module
from typing import Any, Dict, List

class AIReportGenerator:
    def __init__(self) -> None: ...
    def generate_report(self, data: Any) -> str: ...
    def create_dashboard(self, data: Any) -> Dict[str, Any]: ...
    def export_report(self, report: str, format: str) -> str: ...
